language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: fpK2U3F4SW01VRAMbsdQcnmHDRxkdiq3Qv66UkleGvXgfkiN0XhYZTNd/mIrQi3TIXiUU71TyDw08I1sTgrbZbCYDC2+8FB+Xe8S8HhFUSfnGre7JFzdIR3X7kx5MNHhGVbBerxH2IYJemp0CMASiDIX+Fnt0ZMSfYxToNwY8myQ0kaOPM4OqfpXDlBu9kd/f5713oefpgaYUDRl7Kjj97qktTBo/0Yv8gRFxKypKSiaDwVxilqp/LC/T9m7/hzeS1Rq0Ar5Ko4j+XYOW7B5JUNSk1IuoasuqZfvYW5Ea3fASjwGzAWUM64V20d/j7HxrBDPYNhA8SFGrEwxWbZZbi6fFTcU56VkOHG9VwsGh4/AOz6HxqNzdIpRaAFw3Exwh2wkF5tP3hEru8pr/O5rOCItgmF5lqfiMw0Zkuot7RGQ5f69DagGKjZD7qfiGuAqz87OooGNRJuijGrxmdYlMWyCm1WKxD46qQgF+g3Ao9A2iu9gkq7yldQocGBbCCyil8iMOECiD1MXnygQEvkX0UuZoIAMncKlYiTkHQLE/q/1DFXQL0ZtFkul6gnJSt/0Gd0z2nTrmrnd6pullkzYp8JrUya7hze9m+sk9OV0KPkQI1+jwpgJSlu7TpIsKAQ2cyw4kqgm9RsjnHfmL3GQHj4+6FikMC10WQEqH8y8HZ0=
  app: shielded-tundra-33695
  on:
    repo: Robb42/blogAPI
